### ISSUE TITLE
"Lockout"; preventing use of in game menu options

### ISSUE THREAD

**Issue by Gods666thChild** [TalicZealot/SotnKhaosTools#1]
The in game menu selection can be locked out by freezing 03C9A8 to 00FF.
Note that the menu actually uses 4 1 byte values (03c9a8, a9, aa, ab).
If only the first value is frozen the player, spamming up and down, can rollover into the other values and when the first value is returned to 00 to end the effect it wont show the red menu selector until the player reverses the required amount of presses.
03C9A8 must be frozen at 00FF to properly work and unfrozen to 0000 to bring the red menu selector back to the Equip slot.

I've demonstrated this working effect in a video. 
https://www.youtube.com/watch?v=95mPeqn94nE

**Comment by Gods666thChild** [comment]
i was expecting the "enhancement" label to apply but it goes without saying this is a feature request.

**Comment by TalicZealot** [comment]
I didn't include a feature request template for this since there is no public Twitch service running anymore and I'm not actively gonna work on this.

The address always been in the api under GameApi.CurrentMainMenuCategory. Used in Co-Op. 
Preventing the player from menuing would be more of an inconvenience than anything interesting, so I don't see myself going that route.
